pipeline:
  gradle-test:
    image: docker.faavne.no/lgradle:latest
    pull: true
    when:
      event:
        - push
        - tag
        - pull_request
        - deployment
      branch:
        exclude: [ staging ]

    commands:
      - gradle --version
      - gradle test

  gradle-build:
    image: docker.faavne.no/lgradle:latest
    pull: true
    when:
      event:
        - push
        - deployment
        - tag
        

    commands:
      - gradle build
  
  build-zip:
    image: kramos/alpine-zip
    group: docker
    when:
      event:
        - tag
    commands:
      - cp -r ./runners ./deploy
      - cp ./build/libs/* ./deploy
      - cd ./deploy
      - for file in *.txt; do mv -- "$file" "$${file%%.txt}"; done
      - cd ..
      - zip -r sims-api_${DRONE_TAG}.zip ./deploy


  docker-build:
    group: docker
    image: plugins/docker
    when:
      event:
        - push
        - deployment
      branch:
        - staging
      
    repo: docker.faavne.no/sims
    registry: docker.faavne.no
    dockerfile: Dockerfile.prod
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
  

  docker-stable:
    group: docker
    image: plugins/docker
    when:
      event:
        - tag
      
    repo: docker.faavne.no/sims
    registry: docker.faavne.no
    dockerfile: Dockerfile.prod
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
      - stable

  deploy-zip:
    group: deploy
    image: appleboy/drone-scp
    host: faavne.no
    username: root
    key_path: /ssh/id_rsa
    when:
      event:
        - tag
    target:
      - /mnt/nginx-fs/files/public/sims/releases/sims-api
    source:
      - ./sims-api_${DRONE_TAG}.zip
    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa

  deploy:
    image: appleboy/drone-ssh
    group: deploy
    host: faavne.no
    port: 22
    username: root
    key_path: /ssh/id_rsa
    secrets: [docker_username, docker_password]
    when:
      event:
        - push
        - deployment
        - tag
      branch:
        - staging
    
    script:
      - cd /srv/sims
      - docker login -u $${docker_username} -p $${docker_password}
      - docker-compose pull
      - docker-compose down
      - docker-compose up -d
    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa
