pipeline:
  gradle-test:
    group: gradle
    image: lgradle:jdk8
    pull: true
    when:
      event:
        - push
        - tag
        - pull_request
        - deployment

    commands:
      - gradle --version
      - gradle test

  gradle-build:
    group: gradle
    image: lgradle:jdk8
    pull: true
    when:
      event:
        - push
        - deployment
        - tag
        
      branch:
        - staging

    commands:
      - gradle build
  
  docker-build:
    group: docker
    image: plugins/docker
    pull: true
    when:
      event:
        - push
        - deployment
      branch:
        - staging
      
    repo: docker.faavne.no/sims
    registry: docker.faavne.no
    dockerfile: Dockerfile.prod
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
  

  docker-stable:
    group: docker
    image: plugins/docker
    pull: true
    when:
      event:
        - tag
      branch:
        - staging
      
    repo: docker.faavne.no/sims
    registry: docker.faavne.no
    dockerfile: Dockerfile.prod
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
      - stable

  deploy:
    image: docker/compose:1.19.0
    when:
      event:
        - push
        - deployment
        - tag
      branch:
        - staging
    
    commands:
      - cd /deploy/sims
      - docker-compose down
      - docker-compose pull
      - docker-compose up -d

    volumes:
      - /srv/sims:/deploy/sims