pipeline:
  gradle-test:
    group: gradle
    image: docker.faavne.no/lgradle:latest
    pull: true
    when:
      event:
        - push
        - tag
        - pull_request
        - deployment
      branch:
        exclude: [ staging ]

    commands:
      - gradle --version
      - gradle test --no-daemon

  gradle-build:
    group: gradle
    image: docker.faavne.no/lgradle:latest
    pull: true
    when:
      event:
        - push
        - deployment
        - tag
        
      branch:
        - staging

    commands:
      - gradle build --no-daemon
  
  docker-build:
    group: docker
    image: plugins/docker
    when:
      event:
        - push
        - deployment
      branch:
        - staging
      
    repo: docker.faavne.no/sims
    registry: docker.faavne.no
    dockerfile: Dockerfile.prod
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
  

  docker-stable:
    group: docker
    image: plugins/docker
    when:
      event:
        - tag
      branch:
        - staging
      
    repo: docker.faavne.no/sims
    registry: docker.faavne.no
    dockerfile: Dockerfile.prod
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
      - stable

  deploy:
    image: appleboy/drone-ssh
    host: faavne.no
    port: 22
    username: root
    key_path: /ssh/id_rsa
    secrets: [docker_username, docker_password]
    when:
      event:
        - push
        - deployment
        - tag
      branch:
        - staging
    
    script:
      - cd /srv/sims
      - docker login -u $${docker_username} -p $${docker_password}
      - docker-compose pull
      - docker-compose down
      - docker-compose up -d
    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa
